export const _glaDomains = [
  {
    id: 'district-governance',
    name: 'District Governance',
    shortName: 'Governance',
    description: 'Local service delivery, public administration, resource allocation, and implementation tracking.',
    icon: 'solar:buildings-3-outline',
    color: 'primary',
    status: 'Ready',
    priority: 'High',
    audience: 'District teams, public administrators, community coordinators',
    inputs: ['Departments', 'Community needs', 'Budget assumptions', 'Service goals', 'Timeline', 'Risks', 'KPIs'],
    methods: ['Stakeholder Mapping', 'Resource Planning', 'Service KPI Tracking', 'Public Feedback Loop'],
    sections: ['Service delivery actions', 'Department owners', 'Budget notes', 'Community risks', 'KPI review'],
    sampleObjective: 'Improve district-level education service delivery over the next 6 months.',
  },
  {
    id: 'global-leadership',
    name: 'Global Leadership',
    shortName: 'Leadership',
    description: 'Leadership strategy, collaboration, policy alignment, stakeholder communication, and impact leadership.',
    icon: 'solar:global-outline',
    color: 'info',
    status: 'Ready',
    priority: 'High',
    audience: 'Candidates, leadership teams, program directors',
    inputs: ['Leadership objectives', 'Stakeholders', 'Communication model', 'Decision framework', 'Expected influence'],
    methods: ['Decision Framework', 'Influence Mapping', 'Communication Model', 'Policy Alignment'],
    sections: ['Leadership intent', 'Stakeholder influence', 'Decision cadence', 'Communication plan', 'Impact signals'],
    sampleObjective: 'Create a stakeholder communication model for a regional leadership initiative.',
  },
  {
    id: 'development-planning',
    name: 'Development Planning',
    shortName: 'Development',
    description: 'Economic and social development initiatives, implementation roadmaps, and impact tracking.',
    icon: 'solar:chart-square-outline',
    color: 'success',
    status: 'Ready',
    priority: 'High',
    audience: 'Development teams, NGOs, coordinators, analysts',
    inputs: ['Problem statement', 'Beneficiaries', 'Resources', 'Milestones', 'Impact KPIs', 'Sustainability plan'],
    methods: ['Problem Framing', 'Milestone Roadmap', 'Impact KPI Model', 'Sustainability Review'],
    sections: ['Problem definition', 'Beneficiary model', 'Resource plan', 'Milestones', 'Sustainability checks'],
    sampleObjective: 'Plan a community skills program with measurable social and economic impact.',
  },
  {
    id: 'world-trade-planning',
    name: 'World Trade Planning',
    shortName: 'Trade',
    description: 'Trade strategy, market entry, export/import planning, partnership mapping, and trade policy review.',
    icon: 'solar:box-minimalistic-outline',
    color: 'warning',
    status: 'Draft',
    priority: 'Medium',
    audience: 'Trade planners, exporters, partnership managers',
    inputs: ['Target market', 'Products/services', 'Compliance', 'Logistics', 'Risks', 'Trade opportunity', 'Cost-benefit'],
    methods: ['Market Entry Scan', 'Compliance Review', 'Partner Mapping', 'Logistics Risk Review'],
    sections: ['Market opportunity', 'Compliance needs', 'Logistics assumptions', 'Partner map', 'Cost-benefit notes'],
    sampleObjective: 'Assess a low-risk market entry plan for regional agricultural exports.',
  },
  {
    id: 'education-planning',
    name: 'Education Planning',
    shortName: 'Education',
    description: 'School, university, or program planning with learning outcomes, delivery model, and review.',
    icon: 'solar:notebook-bookmark-outline',
    color: 'secondary',
    status: 'Ready',
    priority: 'High',
    audience: 'Education leaders, program teams, curriculum reviewers',
    inputs: ['Audience', 'Curriculum goals', 'Delivery model', 'Resources', 'Assessment method', 'Improvement plan'],
    methods: ['Outcome Mapping', 'Curriculum Alignment', 'Assessment Design', 'Improvement Cycle'],
    sections: ['Learning outcomes', 'Delivery model', 'Resource plan', 'Assessment approach', 'Improvement loop'],
    sampleObjective: 'Design a blended learning program with clear outcomes and assessment checkpoints.',
  },
];

export const _glaMethods = [
  { id: 'stakeholder-mapping', name: 'Stakeholder Mapping', domainIds: ['district-governance', 'global-leadership'], effort: 2, value: 5 },
  { id: 'resource-planning', name: 'Resource Planning', domainIds: ['district-governance', 'development-planning', 'education-planning'], effort: 3, value: 4 },
  { id: 'kpi-tracking', name: 'KPI Tracking', domainIds: ['district-governance', 'development-planning'], effort: 2, value: 4 },
  { id: 'decision-framework', name: 'Decision Framework', domainIds: ['global-leadership'], effort: 3, value: 5 },
  { id: 'milestone-roadmap', name: 'Milestone Roadmap', domainIds: ['development-planning', 'education-planning'], effort: 3, value: 4 },
  { id: 'market-entry-scan', name: 'Market Entry Scan', domainIds: ['world-trade-planning'], effort: 4, value: 4 },
  { id: 'compliance-review', name: 'Compliance Review', domainIds: ['world-trade-planning'], effort: 4, value: 5 },
  { id: 'assessment-design', name: 'Assessment Design', domainIds: ['education-planning'], effort: 2, value: 4 },
];

export const _glaPlanTemplate = {
  objective: '',
  context: '',
  audience: '',
  timeline: '6 months',
  constraints: '',
  expectedOutcome: '',
  actions: 'Define three priority actions and owners for the selected planning domain.',
  stakeholders: 'Identify primary decision makers, reviewers, and impacted groups.',
  resources: 'List budget assumptions, people, data, tools, and external dependencies.',
  risks: 'Document adoption risks, timeline risks, compliance risks, and mitigation steps.',
  kpis: 'Add measurable success indicators and review frequency.',
  milestones: 'Outline the first 30, 60, and 90 day implementation checkpoints.',
};

export const _glaCostBenefit = {
  effortScore: 3,
  impactScore: 4,
  valueScore: 4,
  riskScore: 2,
  feasibilityScore: 4,
};

export const _glaReviewQueue = [
  {
    id: 'GLA-1001',
    title: 'District education service delivery plan',
    domain: 'District Governance',
    owner: 'Candidate Demo',
    status: 'Ready for review',
    completeness: 92,
    reviewer: 'Evaluator',
    dueDate: 'Day 5',
  },
  {
    id: 'GLA-1002',
    title: 'Regional leadership communication model',
    domain: 'Global Leadership',
    owner: 'Leadership Team',
    status: 'Needs changes',
    completeness: 74,
    reviewer: 'Coordinator',
    dueDate: 'Day 6',
  },
  {
    id: 'GLA-1003',
    title: 'Blended learning implementation plan',
    domain: 'Education Planning',
    owner: 'Program Lead',
    status: 'Approved',
    completeness: 100,
    reviewer: 'Client Stakeholder',
    dueDate: 'Complete',
  },
];
